language: objective-c
osx_image: xcode9.2

cache:
  ccache: true
  bundler: true
  cocoapods: true
  directories:
    - node_modules
    - $HOME/Library/Caches/Homebrew
    - $HOME/.cocoapods

# env:
#   global:
#   - NODE_VERSION=stable

before_install:
  - brew install ccache
  - nvm install 8
  - node --version

install:
  - npm install

script:
  - npm run lint
  - npm run test

  - (cd ios; pod install --repo-update; cd -)
  - npm install -g react-native-cli
  - npm install -g detox-cli
  - brew tap wix/brew
  - brew install applesimutils --HEAD
  - detox build --configuration ios.sim.release --silent
  - detox test --configuration ios.sim.release --cleanup
  - git status
