language: objective-c
osx_image: xcode9.2

cache:
  timeout: 900
  ccache: true
  directories:
    - node_modules
    - $HOME/Library/Caches/Homebrew
    - $HOME/.cocoapods

before_install:
  - brew install ccache
  - nvm install 8
  - node --version
  - npm install -g react-native-cli
  - npm install -g detox-cli
  - gem install xcpretty
  - brew tap wix/brew
  - brew install applesimutils --HEAD

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - detox build --configuration ios.sim.release
  - detox test --configuration ios.sim.release --cleanup
  - ./scripts/travis.sh
